name: REMARKER BUILDS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  build:
    runs-on: ubuntu-latest
    environment: BUILD
    env:
      GITHUB_TOKEN: ${{secrets.REMARKER_TOKEN}}
      REMARKER_IMAGE_NAME: "docker.io/${{secrets.DOCKER_USERNAME}}/remarker"
    steps:
    - uses: actions/checkout@v3
      
    # - name: Set up Go
    #   uses: actions/setup-go@v4
    #   with:
    #     go-version: '1.20'
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        

    # - name: Extract metadata (tags, labels) for Docker
    #   id: meta
    #   uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
    #   with:
    #     images: ${{ env.REMAKER_IMAGE_NAME }}
        
    - name: Build and push Docker image
      # uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      # with:
      #   context: .
      #   file: ./Dockerfile
      #   push: true
      #   tags: "latest" # ${{ steps.meta.outputs.tags }}
      #   labels: ${{ steps.meta.outputs.labels }}
      run: |
        docker build --rm --build-arg GITHUB_TOKEN="${{env.GITHUB_TOKEN}}" -t ${{env.REMARKER_IMAGE_NAME}}:latest -f Dockerfile
        docker push ${REMARKER_IMAGE_NAME}:latest